# it is possible to use Travis to upload snapshots to Bintray
# and releases to Bintray/GitHub/JCenter,
# but it requires storing API keys, duplicating Bintray configuration etc.,
# and I am not planning on doing it now.
language: scala
scala: 2.12.8
#jdk: oraclejdk8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
