steps:
  - name: 'gcr.io/cloud-builders/gradle'
    args: [':service:copyDockerResources']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/service', './service/build/docker']
images: ['gcr.io/$PROJECT_ID/service']
