steps:
# gradle: prepare docker context
  - name: 'gcr.io/cloud-builders/gradle'
    args: [':service:prepareDockerContext']
# docker: build docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/service', './service/build/docker']
# docker: push the image (as part of the build)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/service']
# gcloud: update VM instance's image
  - name: gcr.io/cloud-builders/gcloud
    args: ['compute', 'instances', 'update-container', '--zone', 'us-east1-b', 'instance-1', '--container-image=gcr.io/$PROJECT_ID/service']
# also display the image in the build results
images: ['gcr.io/$PROJECT_ID/service']
