steps:
# gradle: prepare docker context
# Latest Gradle builder on Google Cloud Build is v4.6; I need v5.0,
# so I am using a custom builder I had to build myself:
#  - name: 'gcr.io/cloud-builders/gradle'
  - name: 'gcr.io/calendar-service-1/gradle:5.0-jdk-8'
    args: [':service:prepareDockerContext']

# docker: build docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
    - 'build'
    - '--tag=gcr.io/$PROJECT_ID/service'
    - './service/build/docker'
#waitFor: ['-']

# docker: push the image (as part of the build)
  - name: 'gcr.io/cloud-builders/docker'
    args:
    - 'push'
    - 'gcr.io/$PROJECT_ID/service'
#waitFor: ['-']

# gcloud: update VM instance's image
#   this is specific to my particular setup: one VM instance named 'instance-1' in a specific zone.
  - name: gcr.io/cloud-builders/gcloud
    args:
    - 'compute'
    - 'instances'
    - 'update-container'
    - '--zone=us-east1-b'
    - 'instance-1'
    - '--container-image=gcr.io/$PROJECT_ID/service'

# also display the image in the build results
images: ['gcr.io/$PROJECT_ID/service']
