title: "Rambam on Jewish Calendar"
author: "Leonid Dubinsky"
email: dub@podval.org

description: >- # this means to ignore newlines until "baseurl:"
  Code for working with Jewish calendar, both arithmetic and astronomical.
  Some remarks.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.jewish-calendar.org"

github_username:  dubinsky

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - CHANGELOG.md

markdown: kramdown
theme: minima

#include:
#  - README.md

exclude:
  - build.gradle
  - build
  - Gemfile
  - Gemfile.lock
  - CNAME
  - tut

timezone: America/New_York
