title: "Open Torah Project"
author: "Leonid Dubinsky"
email: dub@podval.org

description: >- # this means to ignore newlines until "baseurl:"
  Digital Judaica Done Right :)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.opentorah.org" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  dubinsky

header_pages:
  - index.md
  - CHANGELOG.md

markdown: kramdown
theme: minima

exclude:
  - build.gradle
  - build
  - Gemfile
  - Gemfile.lock
  - CNAME

timezone: America/New_York
