title: "Digital Judaica Done Right"
author: "Leonid Dubinsky"
email: dub@podval.org

description: >- # this means to ignore newlines until "baseurl:"
  Digital Judaica Done Right :)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.opentorah.org" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  dubinsky

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - index.md

markdown: kramdown
theme: minima

#include:
#  - README.md

exclude:
  - build.gradle
  - build
  - Gemfile
  - Gemfile.lock
  - CNAME

timezone: America/New_York
