apiVersion: "serving.knative.dev/v1"
kind: "Service"
metadata:
  name: "collector"
  annotations:
    run.googleapis.com/launch-stage: "BETA"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "100"
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - image: "gcr.io/alter-rebbe-2/collector"
        ports:
        - containerPort: 8080
        env:
          - name: "STORE"
            value: "http://opentorah.github.io/alter-rebbe.org/"
        resources:
          limits:
            cpu: "1000m"
            memory: "256Mi"
      containerConcurrency: 80
      timeoutSeconds: 300
