name: "CI"
on:
  push:
    branches:
      - 'master'


jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - name: "Check out the code"
        uses: actions/checkout@v1

      - name: "Set up JDK 1.8"
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: "Build with Gradle and publish the packages"
        run: ./gradlew build publish
        env:
          GITHUB_TOKEN: ${{github.token}}

