name: "CI"
on:
  push:
    branches:
      - 'master'


jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - name: "Check out the code"
        uses: actions/checkout@master

      - name: "Set up JDK 1.8"
        uses: actions/setup-java@master
        with:
          java-version: 1.8

      - name: "Build and test"
        run: ./gradlew --no-daemon build

      - name: "Upload to Bintray"
        env:
          bintrayApiKey: ${{secrets.bintrayApiKey}}
        run: ./gradlew --no-daemon bintrayUpload

      - name: "Build and push container image to Google Container Registry and deploy Cloud Run service"
        env:
          gcloudServiceAccountKey: ${{secrets.gcloudServiceAccountKey}}
        run: ./gradlew --no-daemon deploy
