name: "CI"
on:
  push:
    branches:
      - 'master'


jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - name: "Check out the code"
        uses: actions/checkout@master

      - name: "Set up JDK 1.8"
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: "Build with Gradle"
        run: ./gradlew --no-daemon build

#      - name: "Upload to Bintray"
# TODO use findProperty | System.getEnv and package the secrets into env:
#        run: ./gradlew -PbintrayApiKey=${{secrets.bintrayApiKey}} bintrayUpload

#      - name "Publish plugins"
#        run: ./gradlew -Pgradle.publish.key=${{secrets.gradlePluginPortalKey}} -Pgradle.publish.secret=${{secrets.gradlePluginPortalSecret}} publishPlugins
