name: "CI"
on:
  push:
    branches:
      - 'master'


jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - name: "Check out the code"
        uses: actions/checkout@master

      - name: "Set up Java"
        uses: actions/setup-java@master
        with:
          java-version: 11

#      - name: "Build and test"
#        run: ./gradlew --no-daemon --console=plain build

      - name: "Assemble"
        run: ./gradlew --no-daemon --console=plain assemble

#      - name: "Upload to Bintray"
#        env:
#          bintrayApiKey: ${{secrets.bintrayApiKey}}
#        run: ./gradlew --no-daemon --console=plain bintrayUpload

      - name: "Build and push container image to GCR and deploy Cloud Run service"
        env:
          gcloudServiceAccountKey: ${{secrets.gcloudServiceAccountKey}}
        run: ./gradlew --no-daemon --console=plain deploy
